services:
  library_web:
    image: ${DOCKER_REGISTRY-}libraryweb
    build:
      context: .
      dockerfile: Library_Web/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001" 

  library_database:
    image: postgres:latest  
    container_name: library_database
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/library-db:/var/lib/postgresql/data 
    ports:
      - 5432:5432